name: Run Python script every day at 1 AM UTC

on:
  schedule:
    - cron: '0 1 * * *'  
  workflow_dispatch:      # Manual run option

env:
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python news_scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add news_*.csv
          git commit -m "Add news data $(date -u)"
          git push
